name: Deploy to Streamlit Cloud

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f streamlit_requirements.txt ]; then pip install -r streamlit_requirements.txt; else pip install -r requirements.txt; fi
          
      - name: Test Streamlit app
        run: |
          echo "Testing Streamlit app..."
          # Add any tests you want to run here
          
      - name: Deploy info
        run: |
          echo "Your app is ready for deployment on Streamlit Cloud!"
          echo "Visit https://streamlit.io/cloud to deploy your app manually."
          echo "Connect your GitHub repository and select movie_recommender.py as the main file." 